name: Serverspec

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        ruby-version: ['3.4', '4.0']
      fail-fast: false

    name: Ruby ${{ matrix.ruby-version }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      env:
        DOCKER_BUILDKIT: 1
      run: bundle exec rake
